### ISSUE TITLE
Daily update log link is not visible to public

### ISSUE THREAD

**Issue by Logan1x** [nikhita/gsoc-meta-k8s#49]
Docs sharing link in readme of daily update log is not open for public.

**Comment by nikhita** [comment]
@Logan1x That's intentional. :)

This repo was also a landing page for mentors, etc to check up on progress if needed and it's accessible to them. The notes contain some of the chats/DMs/discussions I've had regarding bugs, etc and I don't think it's right to make them public because they were private discussions.

I've collated the general idea behind each week as `weekly notes`. Please feel free to go through them. :)
